name: test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  only-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        run: |
          cd molpy/molcpp
          cmake --preset=dev-linux
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-cmake@v10.5
        with:
          # You may need to change the path here
          workflowPreset: vcpkg

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: lukka/get-cmake@latest
      - run: |
          cd molpy
          pip install .
